version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: hogaru_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - hogaru_data:/var/lib/postgresql/data

volumes:
  hogaru_data: